apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: trip
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofilepod
  template:
    metadata:
      labels:
        app: userprofilepod
    spec:
      containers:
      - name: userprofile
        image: registryupn5885.azurecr.io/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_USERNAME
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_SERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_DBNAME
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 1Gi

        